In [1]:
#Test
print('Hello, World!')

Hello, World!


In [3]:
import numpy as np

x = np.arange(2,34,2)
print(x)


[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32]


In [18]:
# Boolean Indexing, Set Operations, and Sorting in NumPy
import numpy as np

x = np.arange(25).reshape(5, 5)

print("Original Array:")
print(x)	


# We can use boolean indexing to also specify the place where we want to modify

x[(x>10) & (x<20)] = -1

print("\nModified Array:")
print(x)

# Sorting
y = np.random.randint(0, 100, size=(100,))
print("\nUnsorted Array:")
print(y)

y_sorted = np.sort(y)
print("\nSorted Array:")
print(y_sorted)
print("\n Original Array after sorting (remains unchanged):")
print(y)

Original Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Modified Array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [20 21 22 23 24]]

Unsorted Array:
[30 36 46 54 43 74 33 16 45 47 34 49 54 29 77 47 21  7 62 78 24  1 43 64
 14 99 97 73 74 91 30 97 74 37 57 29 13 58  2 84 83 21 12 78 45 35 79 49
 82 39 68 26 88 36 52 94  3 44 70 85 62 42 98 77 98 68 77 24 18 22 87 74
  1 22 89 60 13 17 67 83  4 79 84 33 58  2 60 65 49 89 56 94 17 72 55 16
 34 91  3 10]

Sorted Array:
[ 1  1  2  2  3  3  4  7 10 12 13 13 14 16 16 17 17 18 21 21 22 22 24 24
 26 29 29 30 30 33 33 34 34 35 36 36 37 39 42 43 43 44 45 45 46 47 47 49
 49 49 52 54 54 55 56 57 58 58 60 60 62 62 64 65 67 68 68 70 72 73 74 74
 74 74 77 77 77 78 78 79 79 82 83 83 84 84 85 87 88 89 89 91 91 94 94 97
 97 98 98 99]

 Original Array after sorting (remains unchanged):
[30 36 46 54 43 74 33 16 45 47 34 49 54 29 77 47 21  7 62 78 24  1 43 64
 14 99 97 73 74 

In [34]:
# Simple neural network example using NumPy arrays

x = np.array([[2], [-1], [0.5]]).reshape(3,1)
print("\nInput:\n", x)

weights = np.array([[0.1, 1.0], [-0.3, 0.5], [2.0, -1.0]]).reshape(3,2)
print("\nWeights:\n", weights)

bias = np.array([[0.2], [-0.4]]).reshape(2,1)
print("\nBias:\n", bias)

# First input neuron ftakes 3 weights from Weights matrix and does a scalar product
# I need to do y = x^T * weights + bias
y = np.dot(x.T, weights) + bias.T
print("\nOutput:\n", y)	

# Every single row of the input data is being multiplied by the weight number
# We create a count matrix in order to count in at once using a GPU not doing loops in loopes


Input:
 [[ 2. ]
 [-1. ]
 [ 0.5]]

Weights:
 [[ 0.1  1. ]
 [-0.3  0.5]
 [ 2.  -1. ]]

Bias:
 [[ 0.2]
 [-0.4]]

Output:
 [[1.7 0.6]]
